/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Property, BusinessSchema } from './types';

export const BUSINESS_DETAILS: BusinessSchema & { description: string } = {
  name: 'Verified Properties',
  tagline: 'Real Estate & Investment Consultant',
  description: 'Your trusted partner for buying, selling, renting, and investing in premium real estate across Naigaon, Vasai, Virar, and the wider Mumbai-Palghar suburbs. With clear RERA verification and deep local market expertise, we build pathways to your dream property and high-yield investments.',
  reraNo: 'A99000026853',
  contactPerson: 'Mansi Gaikwad',
  phone: '7020913759',
  email: 'verifiedproperties20@gmail.com',
  address: {
    shop: 'Nakshatra Primus, A-Wing, Shop No. 9',
    landmark: 'Near Global Arena',
    area: 'Naigaon East',
    city: 'Palghar',
    zip: '401208'
  }
};

export const PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Sunteck WestWorld',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹31 Lakhs',
    numericPriceVal: 3100000,
    priceLabel: '₹31 Lakhs Onwards',
    location: 'Sunteck WestWorld, Near Naigaon Railway Station, Naigaon East, Palghar - 401208',
    area: '392 Sq.Ft. Usable',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: true,
    reraNo: 'P99000017195',
    constructionStatus: 'Available',
    image: 'https://iili.io/CTQW6Hg.md.jpg',
    description: 'Sunteck WestWorld in Naigaon East is a beautifully structured premium residential township offering 1 BHK apartments with modern amenities and scenic open layouts. Perfectly situated near the Naigaon Railway Station, this grand G+22 storey tower features state-of-the-art high-speed elevators, kids play zone, manicured landscaping, multi-tier security, and comprehensive resident parking.',
    features: [
      '392 Sq.Ft. Usable Carpet Area',
      'G+22 Storey Premium Tower',
      'Modern Amenities',
      'High-Speed Elevators',
      "Children's Play Area",
      'Landscaped Garden',
      '24x7 Security',
      'Parking Available'
    ],
    gallery: [
      'https://iili.io/CTQW6Hg.md.jpg',
      'https://iili.io/CTQwDIs.md.jpg',
      'https://iili.io/CTQwZpn.md.jpg',
      'https://iili.io/CTQwQkX.md.jpg',
      'https://iili.io/CTQwbhG.md.jpg',
      'https://iili.io/CTQwmQf.md.jpg',
      'https://iili.io/CTQwyB4.md.jpg',
      'https://iili.io/CTQN9El.md.jpg',
      'https://iili.io/CTQNH42.md.jpg',
      'https://iili.io/CTQN3v9.md.jpg'
    ],
    configuration: '1 BHK',
    tower: 'G+22 Storey'
  },
  {
    id: 'prop-002',
    title: 'Sunteck Maxx World',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹33 Lakhs',
    numericPriceVal: 3300000,
    priceLabel: '₹33 Lakhs Onwards',
    location: 'Sunteck Maxx World, Naigaon East, Palghar, Maharashtra',
    area: '407 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'Available',
    image: 'https://iili.io/CuWWQTb.md.jpg',
    description: 'Sunteck Maxx World offers premium 1 BHK smart residential flats with expansive modern layouts in Naigaon East. Built to ultra-premium design standards, the G+23 storey tower provides top-tier urban connectivity, rich community spaces, state-of-the-art elevators, and comprehensive security systems for the perfect lifestyle.',
    features: [
      '1 BHK Smart Homes',
      '407 Sq.Ft Usable Carpet',
      'G+23 Storey Tower',
      'Modern Lifestyle Amenities',
      'Clubhouse',
      "Children's Play Area",
      'Landscaped Gardens',
      'High-Speed Elevators',
      '24x7 Security',
      'Ample Parking'
    ],
    gallery: [
      'https://iili.io/CuWWQTb.md.jpg',
      'https://iili.io/CuWhT0B.md.jpg',
      'https://iili.io/CuWhIfV.md.jpg',
      'https://iili.io/CuWhxiQ.md.jpg',
      'https://iili.io/CuWhuUP.md.jpg',
      'https://iili.io/CuWhlWv.md.jpg',
      'https://iili.io/CuWh0sR.md.jpg',
      'https://iili.io/CuWhczJ.md.jpg',
      'https://iili.io/CuWhYba.md.jpg',
      'https://iili.io/CuWhMgI.md.jpg',
      'https://iili.io/CuWhjbs.md.jpg',
      'https://iili.io/CuWhX5X.md.jpg',
      'https://iili.io/CuWhhen.md.jpg',
      'https://iili.io/CuWhNzG.md.jpg',
      'https://iili.io/CuWhOXf.md.jpg'
    ],
    configuration: '1 BHK',
    tower: 'G+23 Storey'
  },
  {
    id: 'prop-003',
    title: 'Nakshatra Nirvaana',
    builder: 'JSB GROUP',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹36.49 Lakhs',
    numericPriceVal: 3649000,
    priceLabel: '₹36.49 Lakhs Onwards',
    location: 'Nakshatra Nirvaana, Naigaon East, Palghar, Maharashtra',
    area: '1 & 2 BHK',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'Booking Open',
    image: 'https://iili.io/CYRGDSS.md.jpg',
    description: 'Experience premium family living at Nakshatra Nirvaana by JSB Group. Located in the heart of Naigaon East, this thoughtfully planned residential community offers spacious 1 & 2 BHK apartments, a Grand Double Clubhouse, over 30 lifestyle amenities, excellent connectivity, and possession within 2026. Designed for comfort, convenience, and long-term value, Nakshatra Nirvaana is the perfect choice for modern families.',
    features: [
      'Grand Double Clubhouse',
      'Lavish 1 & 2 BHK Apartments',
      'Ground +22 Storey Tower',
      '30+ Premium Amenities',
      'Railway Station within 3 Min',
      'Municipal Water Supply',
      'Secure Gated Community',
      'Pay Only 10% Booking'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.03.41_1_pazzkm.mp4',
      'https://iili.io/CYRGDSS.md.jpg',
      'https://iili.io/CYRWTap.md.jpg',
      'https://iili.io/CYRWoMJ.md.jpg',
      'https://iili.io/CYRWnna.md.jpg',
      'https://iili.io/CYRGyNe.md.jpg',
      'https://iili.io/CYRwAfs.md.jpg',
      'https://iili.io/CYRGpR9.md.jpg'
    ],
    configuration: '1 & 2 BHK',
    tower: 'Ground +22 Storey',
    highlights: [
      'Grand Double Clubhouse',
      'Lavish 1 & 2 BHK Apartments',
      'Ground +22 Storey Tower',
      '30+ Premium Amenities',
      'Railway Station within 3 Minutes',
      'Schools & Colleges Nearby',
      'Hospitals Nearby',
      'Municipal Water Supply',
      '24×7 Water for Flushing & Gardening',
      'Secure Gated Community',
      'Upcoming Bullet Train Connectivity',
      'Premium Construction Quality',
      'Family Friendly Environment',
      'Excellent Investment Opportunity',
      'Pay Only 10% Booking Amount'
    ],
    amenities: [
      { name: 'Grand Clubhouse', icon: 'building' },
      { name: 'Fully Equipped Gymnasium', icon: 'dumbbell' },
      { name: 'Indoor Games', icon: 'gamepad' },
      { name: 'Outdoor Games', icon: 'activity' },
      { name: 'Jogging Track', icon: 'map' },
      { name: 'Yoga & Meditation Zone', icon: 'sparkles' },
      { name: 'Kids Play Area', icon: 'smile' },
      { name: 'Landscaped Garden', icon: 'flower' },
      { name: 'Senior Citizen Zone', icon: 'users' },
      { name: 'CCTV Security', icon: 'video' },
      { name: 'High-Speed Elevators', icon: 'arrow-up-down' },
      { name: 'Fire Fighting System', icon: 'flame' },
      { name: 'Ample Parking', icon: 'car' },
      { name: 'Power Backup', icon: 'zap' },
      { name: 'Rainwater Harvesting', icon: 'flower' },
      { name: 'Intercom Facility', icon: 'phone' }
    ],
    advantages: [
      { name: 'Naigaon Railway Station – 3 Minutes', icon: 'train' },
      { name: 'Schools & Colleges Nearby', icon: 'graduation-cap' },
      { name: 'Multi-Speciality Hospitals Nearby', icon: 'heart-pulse' },
      { name: 'Banks Nearby', icon: 'landmark' },
      { name: 'Temples Nearby', icon: 'milestone' },
      { name: 'Excellent Road Connectivity', icon: 'map' },
      { name: 'Upcoming Bullet Train Corridor', icon: 'train' }
    ]
  },
  {
    id: 'prop-004',
    title: 'AKHAND ELITE',
    builder: 'Team Akhand',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹39.99 Lakhs',
    numericPriceVal: 3999000,
    priceLabel: '₹39.99 L+',
    location: 'Vasai East, Palghar, Maharashtra',
    area: '440 - 710 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'Booking Open',
    image: 'https://iili.io/CY7w30u.md.jpg',
    description: 'Welcome to Akhand Elite, a landmark residential development in Vasai East designed for families who aspire to live a modern and luxurious lifestyle. Featuring spacious 1 & 2 BHK residences with 4 ft. deck balconies, two grand clubhouses, over 30 premium lifestyle amenities, expansive open spaces, and a future-ready location, Akhand Elite offers the perfect combination of comfort, connectivity, and investment potential.',
    features: [
      'G+33 Storey High Rise Tower',
      'Spacious 4 Ft Deck Residences',
      'Two Grand Clubhouses',
      '30+ Luxury Lifestyle Amenities',
      '1 Acre Podium',
      'Ganesha Temple Within Premises',
      '30% Open Green Spaces',
      'Community Lifestyle Zones',
      'Excellent Future Connectivity',
      'Premium Modern Architecture',
      'Family Friendly Living',
      'Excellent Investment Opportunity'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.05.36_d9kq3g.mp4',
      'https://iili.io/CY7w30u.md.jpg',
      'https://iili.io/CY7wFUb.md.jpg',
      'https://iili.io/CY7wfJj.md.jpg'
    ],
    configuration: '1 & 2 BHK',
    tower: 'G+33 Storey',
    highlights: [
      '🏙️ G+33 Storey High Rise Tower',
      '🏡 Spacious 4 Ft Deck Residences',
      '🏊 Two Grand Clubhouses',
      '✨ 30+ Luxury Lifestyle Amenities',
      '🌳 1 Acre Podium',
      '🙏 Ganesha Temple Within Premises',
      '🌿 30% Open Green Spaces',
      '👨👩👧 Community Lifestyle Zones',
      '🚇 Excellent Future Connectivity',
      '🏢 Premium Modern Architecture',
      '🏠 Family Friendly Living',
      '💎 Excellent Investment Opportunity'
    ],
    amenities: [
      { name: 'Two Grand Clubhouses', icon: 'building' },
      { name: 'Swimming Pool', icon: 'zap' },
      { name: 'Fully Equipped Gym', icon: 'dumbbell' },
      { name: 'Indoor Games', icon: 'gamepad' },
      { name: 'Outdoor Sports Area', icon: 'activity' },
      { name: 'Jogging Track', icon: 'map' },
      { name: 'Kids Play Area', icon: 'smile' },
      { name: 'Senior Citizen Zone', icon: 'users' },
      { name: 'Yoga Deck', icon: 'sparkles' },
      { name: 'Meditation Area', icon: 'sparkles' },
      { name: 'Landscaped Gardens', icon: 'flower' },
      { name: 'Ganesha Temple', icon: 'milestone' },
      { name: '1 Acre Podium', icon: 'building' },
      { name: 'Multi-Purpose Hall', icon: 'building' },
      { name: 'High-Speed Elevators', icon: 'arrow-up-down' },
      { name: 'CCTV Surveillance', icon: 'video' },
      { name: '24×7 Security', icon: 'shield' },
      { name: 'Fire Safety System', icon: 'flame' },
      { name: 'Power Backup', icon: 'zap' },
      { name: 'Ample Parking', icon: 'car' },
      { name: 'Rainwater Harvesting', icon: 'flower' },
      { name: 'Intercom Facility', icon: 'phone' }
    ],
    advantages: [
      { name: 'Excellent Road Connectivity', icon: 'map' },
      { name: 'Upcoming Metro & Infrastructure', icon: 'train' },
      { name: 'Schools Nearby', icon: 'graduation-cap' },
      { name: 'Colleges Nearby', icon: 'graduation-cap' },
      { name: 'Hospitals Nearby', icon: 'heart-pulse' },
      { name: 'Shopping Centers Nearby', icon: 'building' },
      { name: 'Railway Station Easily Accessible', icon: 'train' },
      { name: 'Banks & ATMs Nearby', icon: 'landmark' },
      { name: 'Daily Convenience Stores Nearby', icon: 'building' }
    ]
  },
  {
    id: 'prop-005',
    title: 'NAKSHATRA AAZSTHA',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹33.49 Lakhs',
    numericPriceVal: 3349000,
    priceLabel: '₹33.49 L+',
    location: 'Yashwant Smart City, Vasai East, Palghar, Maharashtra',
    area: '390 - 609 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'Booking Open',
    image: 'https://iili.io/CY1qMGt.md.jpg',
    description: 'Introducing Nakshatra Aazstha, a landmark residential development located at Madhuban Gate, Yashwant Smart City, Vasai East. Featuring the tallest residential towers in Vasai, this premium project offers thoughtfully designed 1 & 2 BHK homes, a first-of-its-kind 5-Level Grand Clubhouse, luxury lifestyle amenities, flexible payment plans, and unmatched connectivity. Experience elevated living with modern architecture, world-class facilities, and exceptional investment value.',
    features: [
      'Tallest Residential Towers in Vasai',
      'G+33 Storey Premium High-Rise Towers',
      'Modern Luxury Architecture',
      '5-Level Grand Clubhouse',
      'Premium Lifestyle Community',
      'Excellent Connectivity',
      'Spacious Premium Homes',
      'Family-Friendly Environment',
      'High Investment Potential'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.07.32_eifhqf.mp4',
      'https://iili.io/CY1qMGt.md.jpg',
      'https://iili.io/CY1q1ZN.md.jpg',
      'https://iili.io/CY1qGnI.md.jpg',
      'https://iili.io/CY1IkJt.md.jpg',
      'https://iili.io/CY1Iv5X.md.jpg'
    ],
    configuration: '1 & 2 BHK',
    tower: 'G+33 Storey',
    highlights: [
      '⭐ Tallest Residential Towers in Vasai',
      '🏙️ G+33 Storey Premium High-Rise Towers',
      '🏢 Modern Luxury Architecture',
      '🏊 5-Level Grand Clubhouse',
      '🌿 Premium Lifestyle Community',
      '🚇 Excellent Connectivity',
      '🏡 Spacious Premium Homes',
      '👨👩👧 Family-Friendly Environment',
      '💎 High Investment Potential'
    ],
    configurations: [
      { name: '1 BHK Standard', area: '390 Sq.Ft.', price: '₹33.49 Lakhs' },
      { name: '1 BHK Spacious', area: '409 Sq.Ft.', price: '₹34.20 Lakhs' },
      { name: '1 BHK Grand', area: '416 Sq.Ft.', price: '₹36.00 Lakhs' },
      { name: '2 BHK Standard', area: '502 Sq.Ft.', price: '₹43.80 Lakhs' },
      { name: '2 BHK Luxury', area: '546 Sq.Ft.', price: '₹48.20 Lakhs' },
      { name: '2 BHK Royal', area: '609 Sq.Ft.', price: '₹54.99 Lakhs' }
    ],
    paymentPlans: [
      { title: '5 : 95 Payment Scheme', detail: 'Pay only 5%', extra: '95% through Home Loan' },
      { title: '10 : 90 Payment Scheme', detail: 'Pay only 10%', extra: '90% through Home Loan' },
      { title: 'Builder Subvention Available', detail: 'Easy Payment Plans', extra: 'Special Launch Offers' }
    ],
    grandClubhouse: [
      { level: 'Level 5', items: ['Table Tennis', 'Chess', 'Carrom', 'Indoor Games'] },
      { level: 'Level 4', items: ['Hi-Tech Global Gym', 'Modern Fitness Equipment'] },
      { level: 'Level 3', items: ['Luxury Jacuzzi', 'Relaxation Lounge'] },
      { level: 'Level 2', items: ['Steam Room', 'Spa', 'Sauna'] }
    ],
    launchBenefits: [
      'Choice of Best Inventory',
      'Special Launch Discount',
      'Spot Booking Benefits',
      'Flexible Payment Options',
      'Attractive Home Loan Assistance'
    ],
    amenities: [
      { name: '5-Level Grand Clubhouse', icon: 'building' },
      { name: 'Swimming Pool', icon: 'zap' },
      { name: 'Luxury Jacuzzi', icon: 'sparkles' },
      { name: 'Steam Room', icon: 'flame' },
      { name: 'Spa', icon: 'sparkles' },
      { name: 'Sauna', icon: 'flame' },
      { name: 'Fully Equipped Gym', icon: 'dumbbell' },
      { name: 'Indoor Games', icon: 'gamepad' },
      { name: 'Kids Play Area', icon: 'smile' },
      { name: 'Jogging Track', icon: 'map' },
      { name: 'Yoga Deck', icon: 'sparkles' },
      { name: 'Landscaped Gardens', icon: 'flower' },
      { name: 'Senior Citizen Zone', icon: 'users' },
      { name: 'Multipurpose Hall', icon: 'building' },
      { name: 'High-Speed Elevators', icon: 'arrow-up-down' },
      { name: 'CCTV Surveillance', icon: 'video' },
      { name: '24×7 Security', icon: 'shield' },
      { name: 'Fire Safety System', icon: 'flame' },
      { name: 'Power Backup', icon: 'zap' },
      { name: 'Ample Parking', icon: 'car' },
      { name: 'Rainwater Harvesting', icon: 'flower' },
      { name: 'Intercom Facility', icon: 'phone' },
      { name: 'Premium Entrance Lobby', icon: 'building' },
      { name: 'Community Spaces', icon: 'users' },
      { name: 'Open Green Zones', icon: 'flower' }
    ],
    advantages: [
      { name: 'Yashwant Smart City', icon: 'building' },
      { name: 'Excellent Road Connectivity', icon: 'map' },
      { name: 'Schools Nearby', icon: 'graduation-cap' },
      { name: 'Colleges Nearby', icon: 'graduation-cap' },
      { name: 'Hospitals Nearby', icon: 'heart-pulse' },
      { name: 'Shopping Centres Nearby', icon: 'building' },
      { name: 'Railway Connectivity', icon: 'train' },
      { name: 'Banks & ATMs Nearby', icon: 'landmark' },
      { name: 'Daily Convenience Stores Nearby', icon: 'building' }
    ]
  },
  {
    id: 'prop-006',
    title: 'SUPER HOMEZ',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹27.49 Lakhs',
    numericPriceVal: 2749000,
    priceLabel: '₹27.49 L+',
    location: 'Near Global City, Virar West, Palghar, Maharashtra',
    area: '390 - 546 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'Booking Open',
    image: 'https://iili.io/CYEClPS.md.jpg',
    description: 'Introducing Super Homez, a thoughtfully planned residential community near Global City, Virar West. Own your dream home with an exclusive ₹501 + Taxes booking offer and enjoy No EMI Till Possession. Designed for modern families, Super Homez offers affordable 1 & 2 BHK homes in a well-connected location with everyday conveniences nearby.',
    features: [
      'Near Global City',
      'Affordable Housing',
      '1 & 2 BHK Apartments',
      'Modern Elevators',
      'Landscaped Garden',
      'Children\'s Play Area',
      '24×7 Security',
      'CCTV Surveillance',
      'Ample Parking',
      'Excellent Road Connectivity',
      'Schools Nearby',
      'Hospitals Nearby',
      'Shopping Centres Nearby'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.17.12_fz8ctp.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.14.47_oth6k2.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-23_at_14.14.46_yjerxu.mp4',
      'https://iili.io/CYEClPS.md.jpg'
    ],
    configuration: '1 & 2 BHK',
    tower: 'Premium Towers',
    highlights: [
      'Near Global City',
      'Affordable Housing',
      '1 & 2 BHK Apartments',
      'Modern Elevators',
      'Landscaped Garden',
      'Children\'s Play Area',
      '24×7 Security',
      'CCTV Surveillance',
      'Ample Parking',
      'Excellent Road Connectivity',
      'Schools Nearby',
      'Hospitals Nearby',
      'Shopping Centres Nearby'
    ],
    configurations: [
      { name: '1 BHK', area: '390 Sq.Ft.', price: '₹27.49 Lakhs' },
      { name: '2 BHK', area: '546 Sq.Ft.', price: '₹37.49 Lakhs' }
    ],
    specialOffer: {
      title: '🏆 GHAR KA GOLDEN TICKET',
      mainText: 'Own Your Dream Home with Just ₹501 + Taxes',
      subHeading: 'No EMI Till Possession',
      highlights: [
        'Limited Time Launch Offer',
        'Lowest Booking Amount',
        'Affordable Pricing',
        'No EMI Till Possession',
        'Easy Home Loan Assistance'
      ]
    },
    amenities: [
      { name: 'Landscaped Garden', icon: 'flower' },
      { name: 'Children\'s Play Area', icon: 'smile' },
      { name: 'Indoor Games', icon: 'gamepad' },
      { name: 'Fitness Area', icon: 'dumbbell' },
      { name: 'Jogging Track', icon: 'map' },
      { name: 'Senior Citizen Seating', icon: 'users' },
      { name: 'Multipurpose Hall', icon: 'building' },
      { name: 'CCTV Security', icon: 'video' },
      { name: 'High-Speed Elevators', icon: 'arrow-up-down' },
      { name: 'Fire Safety System', icon: 'flame' },
      { name: 'Power Backup', icon: 'zap' },
      { name: 'Ample Parking', icon: 'car' }
    ],
    advantages: [
      { name: 'Near Global City', icon: 'building' },
      { name: 'Virar Railway Station Connectivity', icon: 'train' },
      { name: 'Schools Nearby', icon: 'graduation-cap' },
      { name: 'Colleges Nearby', icon: 'graduation-cap' },
      { name: 'Hospitals Nearby', icon: 'heart-pulse' },
      { name: 'Shopping Centres Nearby', icon: 'building' },
      { name: 'Daily Convenience Stores Nearby', icon: 'building' },
      { name: 'Excellent Road Connectivity', icon: 'map' }
    ]
  },
  {
    id: 'prop-007',
    title: 'DEVIKA AVENUE',
    builder: 'Devika Developers',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹36.75 Lakhs*',
    numericPriceVal: 3675000,
    priceLabel: '₹36.75 L*',
    location: 'Naigaon West, Palghar',
    area: '410 - 575 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: true,
    reraNo: 'P9900030502',
    constructionStatus: 'BOOKING OPEN',
    image: 'https://iili.io/Canu1Vt.md.jpg',
    description: 'Nestled within a 10-acre integrated land parcel, Devika Avenue is being developed across 2.25 acres, offering spacious homes, quality construction, abundant open spaces, and modern planning for comfortable family living.',
    features: [
      'Prime Connectivity',
      'Spacious Layouts',
      'Competitive Pricing',
      'Trusted Developer',
      'Premium Lifestyle Amenities',
      'Large Open Spaces'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.50.43_txwnbl.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.49.30_ghxehk.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.49.35_kwn3kv.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.49.31_kpmb2u.mp4',
      'https://iili.io/Canu1Vt.md.jpg',
      'https://iili.io/CanuMfn.md.jpg',
      'https://iili.io/CanuVls.md.jpg',
      'https://iili.io/CanuEiX.md.jpg',
      'https://iili.io/CanuWUG.md.jpg',
      'https://iili.io/CanuhJf.md.jpg',
      'https://iili.io/CanujR4.md.jpg',
      'https://iili.io/CanuwOl.md.jpg',
      'https://iili.io/CanuNb2.md.jpg',
      'https://iili.io/CanuexS.md.jpg',
      'https://iili.io/CanukW7.md.jpg',
      'https://iili.io/Canuvs9.md.jpg',
      'https://iili.io/CanuSfe.md.jpg',
      'https://iili.io/CanuU0u.md.jpg'
    ],
    configuration: '1 & 2 BHK',
    tower: 'G + 22 Storey Premium Residential Tower',
    configurations: [
      { name: '1 BHK', area: '410 Sq.Ft.', price: '₹36.75 Lakhs*' },
      { name: '2 BHK', area: '505 Sq.Ft.', price: 'On Request' },
      { name: '2 BHK', area: '575 Sq.Ft.', price: 'On Request' }
    ],
    paymentPlans: [
      { title: '10 : 90 Plan', detail: 'Construction Linked Plan', extra: 'Pay only 10% now. Remaining amount on Possession.' }
    ],
    amenities: [
      { name: 'Indoor Games', icon: 'gamepad' },
      { name: 'BBQ Area', icon: 'flame' },
      { name: 'Jogging Track', icon: 'map' },
      { name: 'Café Lounge', icon: 'coffee' },
      { name: 'Sit-Out Zones', icon: 'users' },
      { name: 'Large Open Spaces', icon: 'flower' }
    ],
    advantages: [
      { name: '10 Min from Mumbai-Ahmedabad Hwy', icon: 'map' },
      { name: '7 Minutes from Naigaon West', icon: 'map' },
      { name: '1.5 KM from Naigaon Station', icon: 'train' },
      { name: '5 Min from Juchandra Station', icon: 'train' }
    ]
  },
  {
    id: 'prop-008',
    title: 'ORNATE SERENITY',
    builder: 'Ornate Developers',
    type: 'apartment',
    transaction: 'sale',
    price: 'Contact for Best Pricing',
    numericPriceVal: 0,
    priceLabel: 'On Request',
    location: 'Naigaon, Vasai',
    area: '500 - 835 Sq.Ft.',
    bedrooms: 1,
    bathrooms: 1,
    reraApproved: false,
    constructionStatus: 'BOOKING OPEN',
    image: 'https://iili.io/CanlnGp.md.jpg',
    description: 'ORNATE SERENITY – NAIGAON | VASAI\n\nWhere Elegance Meets Elevated Living.\n\nStand tall in one of the tallest residential towers in the vicinity—an address that redefines prestige, luxury, and modern lifestyle.\n\nDesigned with spacious homes, bigger carpet areas, airy balconies, and thoughtfully planned layouts for comfortable family living.',
    features: [
      '32 Storey Landmark Tower',
      'Bigger Carpet Areas',
      'Spacious Balconies',
      'Premium Lifestyle',
      'Excellent Connectivity',
      'High Appreciation Potential'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.50.43_wm4x0a.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-26_at_13.50.50_zo9biw.mp4',
      'https://iili.io/CanlnGp.md.jpg',
      'https://iili.io/CanlzFI.md.jpg',
      'https://iili.io/CanlfwJ.md.jpg',
      'https://iili.io/Canlo6N.md.jpg',
      'https://iili.io/CanlIat.md.jpg',
      'https://iili.io/CanlT8X.md.jpg',
      'https://iili.io/CanlA9n.md.jpg',
      'https://iili.io/CanlRus.md.jpg',
      'https://iili.io/Canl5wG.md.jpg',
      'https://iili.io/Canl7tf.md.jpg',
      'https://iili.io/Canl1FS.md.jpg',
      'https://iili.io/CanlfwJ.md.jpg',
      'https://iili.io/Canl7tf.md.jpg',
      'https://iili.io/CanlEc7.md.jpg',
      'https://iili.io/CanlGS9.md.jpg'
    ],
    configuration: '1 & 3 BHK',
    tower: '32 Storey Iconic Residential Tower',
    configurations: [
      { name: '1 BHK', area: '500 Sq.Ft.', price: 'On Request' },
      { name: '3 BHK', area: '835 Sq.Ft.', price: 'On Request' }
    ],
    paymentPlans: [
      { title: 'Stamp Duty Benefit', detail: '0% Stamp Duty Offer', extra: 'Save on your acquisition cost with 0% stamp duty.' },
      { title: 'No EMI Plan', detail: 'No EMI Till Fit-Out Possession', extra: 'Book your dream home and enjoy no EMI pressure until possession.' }
    ],
    amenities: [
      { name: 'Bigger Carpet Areas', icon: 'home' },
      { name: 'Spacious Balconies', icon: 'sunset' },
      { name: 'Premium Lifestyle', icon: 'star' },
      { name: 'Excellent Connectivity', icon: 'map' },
      { name: 'Iconic 32 Storeys', icon: 'building' },
      { name: 'High Appreciation', icon: 'trending-up' }
    ],
    advantages: [
      { name: '32 Storey Landmark Tower', icon: 'building' },
      { name: '30th Slab Successfully Completed', icon: 'check-circle' },
      { name: 'Located at Naigaon, Vasai', icon: 'map' },
      { name: 'Premium Lifestyle & Connectivity', icon: 'map' }
    ]
  },
  {
    id: 'prop-009',
    title: 'NAKSHATRA VEDA – J & E WING',
    builder: 'JSB GROUP',
    type: 'apartment',
    transaction: 'sale',
    price: 'Starting From ₹62 Lakhs*',
    numericPriceVal: 6200000,
    priceLabel: 'Starting From ₹62 L*',
    location: 'Madhuban, Vasai East',
    area: '593 - 943 Sq.Ft. (Carpet)',
    bedrooms: 2,
    bathrooms: 2,
    reraApproved: false,
    constructionStatus: 'BOOKING OPEN',
    image: 'https://iili.io/Canu1Vt.md.jpg',
    description: '🌟 Last Chance to Own Your Premium Home at Nakshatra Veda – J & E Wing, Vasai East!\n\nA prestigious township by JSB Group inside Yashwant Smart City offering premium lifestyle, excellent connectivity, and world-class amenities.',
    features: [
      '23 Storey Premium Tower',
      'Gated Society',
      'JSB Group Development',
      'Located inside Yashwant Smart City',
      '55+ Lifestyle Amenities',
      '6 Acre Modern Township',
      'December 2026 Possession',
      'Premium Residential Community'
    ],
    gallery: [
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-06-27_at_13.15.16_oh31cl.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-07-04_at_03.30.52_pgrk55.mp4',
      'https://res.cloudinary.com/dk9ux64oy/video/upload/WhatsApp_Video_2026-07-04_at_03.31.18_ldoo2o.mp4'
    ],
    configuration: '2 & 3 BHK',
    tower: '23 Storey Premium Tower',
    configurations: [
      { name: '2 BHK Premium', area: '593 Sq.Ft. Usable Carpet', price: 'Starting From ₹62 Lakhs*' },
      { name: '2 BHK Grand', area: '706 Sq.Ft. Carpet', price: 'Starting From ₹66 Lakhs*' },
      { name: '3 BHK Premium', area: '822 Sq.Ft. Usable Carpet', price: 'Starting From ₹86.30 Lakhs*' },
      { name: '3 BHK Grand', area: '943 Sq.Ft. Carpet', price: 'Starting From ₹1 Crore*' }
    ],
    highlights: [
      '23 Storey Premium Tower',
      'Gated Society',
      'JSB Group Development',
      'Located inside Yashwant Smart City',
      '55+ Lifestyle Amenities',
      '6 Acre Modern Township',
      'December 2026 Possession',
      'Premium Residential Community'
    ],
    amenities: [
      { name: '55+ Lifestyle Amenities', icon: 'sparkles' },
      { name: 'Gated Society Security', icon: 'shield' },
      { name: '6 Acre Modern Township', icon: 'building' },
      { name: 'Grand Entrance Lobby', icon: 'smile' },
      { name: 'State-of-the-Art Gym', icon: 'dumbbell' },
      { name: 'Landscaped Gardens', icon: 'flower' }
    ],
    advantages: [
      { name: '8 Minutes from Vasai Railway Station', icon: 'train' },
      { name: '18 Minutes from Mumbai-Ahmedabad Highway', icon: 'map' },
      { name: 'Schools Nearby', icon: 'graduation-cap' },
      { name: 'Colleges Nearby', icon: 'graduation-cap' },
      { name: 'Hospitals Nearby', icon: 'heart-pulse' },
      { name: 'Shopping Centers Nearby', icon: 'building' },
      { name: 'Entertainment Hubs Nearby', icon: 'gamepad' }
    ],
    paymentPlans: [
      { title: 'Subvention Scheme', detail: 'Attractive Home Loan Offers', extra: 'Consult with our representatives for detailed calculations.' },
      { title: 'Builder Approved Plan', detail: 'Flexible Payment Schedules', extra: 'Tailored construction-linked milestones for your comfort.' },
      { title: 'Special Booking Deal', detail: 'Booking Offers Ongoing', extra: 'Secure preferred units with dynamic booking privileges.' }
    ]
  }
];

export const TESTIMONIALS = [
  {
    name: 'Sandeep Raut',
    role: 'Homeowner, Nakshatra Primus',
    text: 'Mansi Gaikwad is incredibly professional. She helped us verify all the legal documentation, RERA registration, and secure a great bank home loan smoothly. Highly recommend Verified Properties!',
    stars: 5,
    location: 'Naigaon East'
  },
  {
    name: 'Anjali Sharma',
    role: 'Business Owner',
    text: 'I was looking for a premium corner shop in Naigaon for my fitness studio. Verified Properties guided me to a prime location with excellent foot traffic. Clear deals with direct builder verification.',
    stars: 5,
    location: 'Naigaon East'
  },
  {
    name: 'Nitin Patil',
    role: 'Investment Partner',
    text: 'As an NRI investor in lands and plots, local trust is paramount. RERA checks and land boundary checks provided by Verified Properties gave me supreme confidence to invest in two land plots in Vasai-Virar.',
    stars: 5,
    location: 'Vasai West'
  }
];
